
import pygame
player_att_images = [[],[]]
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_01.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_01.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_01.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_02.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_02.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_03.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_03.png'))
player_att_images[0].append(pygame.image.load('resources/images/player/player_att_left_04.png'))

player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_01.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_02.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_02.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_02.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_03.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_03.png'))
player_att_images[1].append(pygame.image.load('resources/images/player/player_att_left_top_04.png'))

moon_attacked = []
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked01.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked02.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked02.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked03.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked03.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked04.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked04.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked05.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked06.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked06.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked07.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked07.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked08.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked08.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked09.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked10.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked10.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked11.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked11.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked12.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked12.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked13.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked14.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked14.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked15.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked15.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked16.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked16.png'))
moon_attacked.append(pygame.image.load('resources/images/player/moon/moon_attacked17.png'))





enemy1_images = [[],[]] #0 : dead_ani , 1:alive att_a
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_01.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_02.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_03.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_04.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_05.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_06.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_07.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_08.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_09.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_10.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_10.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_11.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_11.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_12.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_12.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_13.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_13.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_14.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_15.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_16.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_17.png'))
enemy1_images[1].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_left_att_18.png'))

enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_01.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_01.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_02.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_02.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_03.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_03.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_04.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_05.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_06.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_07.png'))
enemy1_images[0].append(pygame.image.load('resources/images/enemy/enemy1/enemy1_die/enemy1_die_08.png'))

enemy2_images = [[],[]] #0 : dead_ani , 1:alive att_a
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_01.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_01.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_02.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_02.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_03.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_03.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_04.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_04.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_05.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_06.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_06.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_07.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_07.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_08.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_08.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_09.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_09.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_09.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_10.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_11.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_11.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_12.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_12.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_13.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_13.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_14.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_14.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_15.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_15.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_16.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_16.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_17.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_17.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_18.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_18.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_19.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_19.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_20.png'))
enemy2_images[1].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_right_att_20.png'))

enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_01.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_01.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_02.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_02.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_03.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_03.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_04.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_05.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_06.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_07.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_08.png'))
enemy2_images[0].append(pygame.image.load('resources/images/enemy/enemy2/enemy2_die_08.png'))





enemy3_images = [[],[]] #0 : dead_ani , 1:alive att_a
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_01.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_02.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_03.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_04.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_04.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_05.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_05.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_05.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_06.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_06.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_06.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_07.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_07.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_08.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_08.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_09.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_09.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_10.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_10.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_11.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_11.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_12.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_12.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_13.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_13.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_13.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_14.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_14.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_15.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_15.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_16.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_16.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_17.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_17.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_18.png'))
enemy3_images[1].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_left_att_18.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_01.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_01.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_02.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_02.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_03.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_03.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_04.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_05.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_06.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_07.png'))
enemy3_images[0].append(pygame.image.load('resources/images/enemy/enemy3/enemy3_die_08.png'))


